name: "Build Android Workflow"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: "11"
        distribution: "adopt"
        cache: "gradle"
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Run YARN Install
      run: |
           cd ./packages/app-mobile
           npm i -g corepack
           yarn install
    - name: Build Application
      run: |
           cd ./packages/app-mobile/android
           ./gradlew assembleDebug    
    - name: Upload application
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./packages/app-mobile/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 3
        

           
