name: "Build Android Workflow"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java_version: "11"
        distribution: "adopt"
        cache: "gradle"
    - name: Validate Gradle Wrapper
      uses: actions/gradle-validation-action@v1
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Run YARN Install
      run: |
           cd ./packages/app-mobile
           npm i -g corepack
           yarn install
    - name: Build Application
      run: |
           cd ./packages/app-mobile/android
           ./gradlew/assembleDebug
    - name: Upload application
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ./packages/app-mobile/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 3
        

           
